### ISSUE TITLE
Citizen alias loading is not very user friendly

### ISSUE THREAD

**Issue by danse** [sourcefabric-innovation/citizendesk-frontend#101]
The loading of a citizen alias (also called "citizen card") page is not very coherent and user friendly. The identity panel appears at first, when nothing is loaded and probably a click would cause an error. Another panel is visible but empty. This is just a second on my machine but it would last longer on a mobile connection.

Panels with buttons should be visible just when the necessary data has been loaded in the controller, hidden panels should be entirely hidden, and not present an empty frame.

Fixing this will probably involve moving some directive one level up on the empty panel, and adding a check on the identity panel. After this, the page will look empty during the loading, so a loading icon could be added, like the one we have in some queues.

**Comment by Flowdeeps** [comment]
Clicking on the "Associate with Identity" button that loads before the panel has finished doesn't cause any issues or stop the page from loading but I agree that it's jarring.

**Comment by danse** [comment]
this has been done, thanks Pete!
