### ISSUE TITLE
Editorial notices to reports

### ISSUE THREAD

**Issue by msat-cont** [sourcefabric-innovation/citizendesk-frontend#33]
We shall allow editors/verifiers to write down notices that shall be displayed for outer viewers/readers. See e.g. the Meta field at:
http://sourcefabric.superdesk.pro/resources/LiveDesk/Blog/1/Post/854

In the report structure, we have "notices_outer" list of dicts that is expected to be used for this use. Each of the dicts in the list shall have (among others) a key "what" with content of the notice, and a key "where" that shall have its value of either "before", or "after".

It can be for a report, like:
{
"_id": ...,
...,
notices_outer: [
    {"what": "this is an SMS", "where": "before"},
    {"what": "it need not be true", "where": "after"}
    ]
}

The stuff in the "what" field shall be filled by editors/verifiers, if they want to.

**Comment by danse** [comment]
This was done with CDTZ-89
